title: My Tech Blog
description: A collection of technical notes, tutorials, and experiments.
author: Bipin Lamichhane  
email: lamichhanebipin1995@gmail.com
#theme: just-the-docs
remote_theme: just-the-docs/just-the-docs
baseurl: "" # Leave this empty for user.github.io, or set to "/repo-name" for project pages
url: "https://bipcode.github.io"

markdown: kramdown
highlighter: rouge

# Optional: social links
github_username: bipcode
linkedin_username: Bipin Lamichhane

# Optional: include these if you want navigation links
show_downloads: true

#favicon
favicon_ico: "favicon.ico"

# Exclude these files from build (optional)
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

defaults:
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "default"

plugins:
  - jekyll-remote-theme
